apiVersion: apps/v1
kind: Deployment
metadata:
  name: Menu-deployment
  labels:
    app: Menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Menu 
  template:
    metadata:
      labels:
        app: Menu
    spec:
      containers:
      - name: Menu
        image: acr20221.azurecr.io/mymenurepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myacrcredentails
---
apiVersion: v1
kind: Service
metadata:
  name: Menusvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Menu